"""news table try fix time

Revision ID: 10d8ad2a7cec
Revises: 45e97afdf225
Create Date: 2020-05-17 22:05:21.411272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10d8ad2a7cec'
down_revision = '45e97afdf225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_news_time', table_name='news')
    op.create_unique_constraint(None, 'news', ['picture'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news', type_='unique')
    op.create_index('ix_news_time', 'news', ['time'], unique=False)
    # ### end Alembic commands ###
