"""news table try fix time.

Revision ID: 1e1caf48fb78
Revises: 10d8ad2a7cec
Create Date: 2020-05-17 22:06:56.620536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e1caf48fb78'
down_revision = '10d8ad2a7cec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_news_time'), 'news', ['time'], unique=False)
    op.create_unique_constraint(None, 'news', ['picture'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news', type_='unique')
    op.drop_index(op.f('ix_news_time'), table_name='news')
    # ### end Alembic commands ###
