"""url table

Revision ID: 20194dbc335e
Revises: 9300ddd12491
Create Date: 2020-05-05 23:05:11.588284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20194dbc335e'
down_revision = '9300ddd12491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('url', sa.String(length=9999), nullable=True),
    sa.ForeignKeyConstraint(['name'], ['news.picture'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_name'), 'link', ['name'], unique=True)
    op.create_unique_constraint(None, 'news', ['picture'])
    op.drop_column('news', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('url', sa.VARCHAR(length=9999), nullable=True))
    op.drop_constraint(None, 'news', type_='unique')
    op.drop_index(op.f('ix_link_name'), table_name='link')
    op.drop_table('link')
    # ### end Alembic commands ###
