"""ads table add column

Revision ID: 258e8cda9ae0
Revises: 3d74f3e9a05e
Create Date: 2020-05-16 21:43:35.466093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258e8cda9ae0'
down_revision = '3d74f3e9a05e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'news', ['picture'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news', type_='unique')
    # ### end Alembic commands ###
