"""news table fix time5.0

Revision ID: 451f6abcd8c9
Revises: 7b88d9072342
Create Date: 2020-05-17 21:56:40.432321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '451f6abcd8c9'
down_revision = '7b88d9072342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_news_time', table_name='news')
    op.create_unique_constraint(None, 'news', ['picture'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news', type_='unique')
    op.create_index('ix_news_time', 'news', ['time'], unique=False)
    # ### end Alembic commands ###
