"""news table fix time6.0

Revision ID: 45e97afdf225
Revises: 451f6abcd8c9
Create Date: 2020-05-17 22:00:17.734989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e97afdf225'
down_revision = '451f6abcd8c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_news_time'), 'news', ['time'], unique=False)
    op.create_unique_constraint(None, 'news', ['picture'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news', type_='unique')
    op.drop_index(op.f('ix_news_time'), table_name='news')
    # ### end Alembic commands ###
