"""abc fix time

Revision ID: 467de01c9a43
Revises: 52b433e902c5
Create Date: 2020-05-17 22:23:55.044329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '467de01c9a43'
down_revision = '52b433e902c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_news_timestamp'), 'news', ['timestamp'], unique=False)
    op.drop_index('ix_news_time', table_name='news')
    op.create_unique_constraint(None, 'news', ['picture'])
    op.drop_column('news', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('time', sa.DATETIME(), nullable=True))
    op.drop_constraint(None, 'news', type_='unique')
    op.create_index('ix_news_time', 'news', ['time'], unique=False)
    op.drop_index(op.f('ix_news_timestamp'), table_name='news')
    op.drop_column('news', 'timestamp')
    # ### end Alembic commands ###
