"""ads table add column

Revision ID: 47ee3464c12c
Revises: e4e0d2005ec0
Create Date: 2020-05-16 20:30:11.837712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47ee3464c12c'
down_revision = 'e4e0d2005ec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads', sa.Column('big', sa.BOOLEAN(), nullable=False))
    op.create_unique_constraint(None, 'news', ['picture'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news', type_='unique')
    op.drop_column('ads', 'big')
    # ### end Alembic commands ###
