"""news table fix time2.0

Revision ID: 51a0878cb691
Revises: 8ce2b7697609
Create Date: 2020-05-17 21:32:32.659204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51a0878cb691'
down_revision = '8ce2b7697609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_news_time'), 'news', ['time'], unique=False)
    op.create_unique_constraint(None, 'news', ['picture'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news', type_='unique')
    op.drop_index(op.f('ix_news_time'), table_name='news')
    # ### end Alembic commands ###
