"""news add column

Revision ID: 6ab6df4d6108
Revises: 80ab43c461f5
Create Date: 2020-05-18 18:46:58.702585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ab6df4d6108'
down_revision = '80ab43c461f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'anime', 'news', ['st_cat'], ['st_cat'])
    op.create_foreign_key(None, 'editor', 'news', ['st_cat'], ['st_cat'])
    op.create_foreign_key(None, 'evaluation', 'news', ['st_cat'], ['st_cat'])
    op.create_foreign_key(None, 'ittime', 'news', ['st_cat'], ['st_cat'])
    op.create_foreign_key(None, 'network', 'news', ['st_cat'], ['st_cat'])
    op.add_column('news', sa.Column('st_cat', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'news', ['picture'])
    op.create_foreign_key(None, 'reward', 'news', ['st_cat'], ['st_cat'])
    op.create_foreign_key(None, 'special', 'news', ['st_cat'], ['st_cat'])
    op.create_foreign_key(None, 'tech', 'news', ['st_cat'], ['st_cat'])
    op.create_foreign_key(None, 'video', 'news', ['st_cat'], ['st_cat'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video', type_='foreignkey')
    op.drop_constraint(None, 'tech', type_='foreignkey')
    op.drop_constraint(None, 'special', type_='foreignkey')
    op.drop_constraint(None, 'reward', type_='foreignkey')
    op.drop_constraint(None, 'news', type_='unique')
    op.drop_column('news', 'st_cat')
    op.drop_constraint(None, 'network', type_='foreignkey')
    op.drop_constraint(None, 'ittime', type_='foreignkey')
    op.drop_constraint(None, 'evaluation', type_='foreignkey')
    op.drop_constraint(None, 'editor', type_='foreignkey')
    op.drop_constraint(None, 'anime', type_='foreignkey')
    # ### end Alembic commands ###
