"""news table add cloumns

Revision ID: 9300ddd12491
Revises: de9b9293139a
Create Date: 2020-05-05 22:08:24.934131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9300ddd12491'
down_revision = 'de9b9293139a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('url', sa.String(length=9999), nullable=True))
    op.create_unique_constraint(None, 'news', ['picture'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news', type_='unique')
    op.drop_column('news', 'url')
    # ### end Alembic commands ###
