"""ads table add column

Revision ID: bf081f7963ba
Revises: bc5900afe57c
Create Date: 2020-05-16 21:29:04.417881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf081f7963ba'
down_revision = 'bc5900afe57c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads', sa.Column('big', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'news', ['picture'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news', type_='unique')
    op.drop_column('ads', 'big')
    # ### end Alembic commands ###
