"""ads table add column

Revision ID: e37f922a337b
Revises: 258e8cda9ae0
Create Date: 2020-05-16 21:55:19.557626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e37f922a337b'
down_revision = '258e8cda9ae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads', sa.Column('big', sa.Boolean(create_constraint='YES', name='NO'), server_default='NO', nullable=False))
    op.create_unique_constraint(None, 'news', ['picture'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news', type_='unique')
    op.drop_column('ads', 'big')
    # ### end Alembic commands ###
